### ISSUE TITLE
Generate templates with case

### ISSUE THREAD

**Issue by sourivore** [DengSir/template-generator-vscode#1]
Hello,

It is not possible to generate template with different cases sensitivity.
It is actually really useful for example with NextJs where pages have to be lowcase and components should be camelCase by convention.

Why not use some `{__name__}`, `{__NAME__}` and `{__Name__}` to be replaced in the correct case ?

Thanks a lot.

**Comment by DengSir** [comment]
Added in 0.3.0

**Comment by DengSir** [comment]
Can use __pascalCaseName__ ?
