### ISSUE TITLE
Can't create file from template in a folder

### ISSUE THREAD

**Issue by dannystaple** [DengSir/template-generator-vscode#2]
I am currently unable to create a folder in a subdirectory. 
When I use the "create file from template" action, and specify a name like "danny_labnotes/2018-01-10", this value is considered an error and is not accepted.

Providing just the name "2018-01-10" is ok though.

**Comment by DengSir** [comment]
You can right click one folder in vscode explorer, and use New File from Template

**Comment by DengSir** [comment]
You can right click one folder in vscode explorer, and use 'New File from Template'

**Comment by dannystaple** [comment]
Happy with that - perhaps you can add it to the docs/readme in the tool?
