### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by gehrenfeld** [DengSir/template-generator-vscode#5]
I have installed the extension but have no idea how to make it work.

I do ctrl P the type Files: and I get no command found.

Thank you

**Comment by DengSir** [comment]
Two ways:
1. ctrl+shift+p, new file from template
2. right click folder in vscode explorer and use "new file from templates"

**Comment by shuv1337** [comment]
Not very helpful. The docs have zero information about how the input file works.
